; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; =========================================================
; SAKLAR PEMILIH FOLDER PROGRAM 
; =========================================================
; src_dir = ESP32main
; src_dir = ESP32_test
src_dir = WT32main
; src_dir = WT32_test
; src_dir = src_mainOTA

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Gunakan partisi Huge APP (3MB) agar Flash 82% tidak error saat linking
; board_build.partitions = huge_app.csv

; =========================================================
; JALANKAN SCRIPT COPY OTOMATIS SETELAH BUILD
; =========================================================
extra_scripts = post:copy_otomatis.py

lib_deps =
    tzapu/WiFiManager @ ^2.0.17
    knolleary/PubSubClient @ ^2.8.0
    bblanchon/ArduinoJson @ ^7.0.4
    miguelbalboa/MFRC522 @ ^1.4.10